import type { Metadata } from "next";

import { Theme } from "@radix-ui/themes";
import { Inter } from "next/font/google";

import "@radix-ui/themes/styles.css";
import "../theme-config.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning className={inter.variable}>
			<body>
				<Theme
					accentColor="brown"
					radius="small"
					appearance="dark"
					scaling="95%"
					grayColor="sand"
					panelBackground="translucent"
				>
					{children}
				</Theme>
			</body>
		</html>
	);
}
